### ISSUE TITLE
keylime.conf lives now in /usr/etc

### ISSUE THREAD

**Issue by dgdavid** [yast/skelcd-control-MicroOS#49]
Our system for detecting [new files in /usr](https://en.opensuse.org/openSUSE:Packaging_UsrEtc) has detected that [_keylime.conf_ is now placed at  _/usr/etc_.](https://github.com/yast/usr-etc-test/runs/4916673864?check_suite_focus=true)

So, I'm wondering if the texts in this control file should be updated accordingly

https://github.com/yast/skelcd-control-MicroOS/blob/6387efe17465556261c923917b4bb6d26ad73b4f/control/control.MicroOS.xml#L595-L606

**Comment by dgdavid** [comment]
@aplanas, @lnussel, what do you think?

**Comment by aplanas** [comment]
Yes, I will address this!

**Comment by aplanas** [comment]
@dgdavid should be part now of https://github.com/yast/skelcd-control-MicroOS/pull/43/commits

**Comment by dgdavid** [comment]
Ok, already addressed in https://github.com/yast/skelcd-control-MicroOS/pull/43.

Thanks for the quick response, @aplanas!
